# Generated by Django 4.0.6 on 2022-07-05 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 13, 38, 13, 32653)),
        ),
    ]
